services:
  postgres:
    image: postgres:16
    container_name: mesos-postgres
    environment:
      POSTGRES_DB: mesos
      POSTGRES_USER: mesos
      POSTGRES_PASSWORD: mesos
    ports:
      - "5432:5432"
    volumes:
      - mesos_postgres_data:/var/lib/postgresql/data

volumes:
  mesos_postgres_data:
